---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
```


#### MVP

## Question 1

```{r}
phone_reviews <- read_csv("data/20190928-items.csv") %>% 
  clean_names()

glimpse(phone_reviews)
```


## Question 2

```{r}
phone_reviews %>% 
  group_by(brand) %>% 
  summarise(n_handsets = n()) %>% 
  arrange(desc(n_handsets)) %>% 
  head(3)
```

Samsung have by far the most handsets in the data set. 


## Question 3

```{r}
samsung_ratings <- phone_reviews %>% 
  filter(brand == "Samsung") 

samsung_stats <- samsung_ratings %>% 
  summarise(
    num = n(), 
    mean = mean(rating), 
    sd = sd(rating)
  )

samsung_stats
```

```{r}
samsung_ratings %>% 
  ggplot(aes(x = rating)) +
  geom_histogram(aes(y = ..density..), col = "white", bins = 25) +
  stat_function(
    fun = dnorm, 
    args = list(
      mean = samsung_stats$mean, 
      sd = samsung_stats$sd
    ), 
    col = "red"
  )
```

Yes I think the normal distribution matches the data set very well. The values to the extreme left are merely outliers. 


## Question 4

1SD
```{r}
samsung_ratings %>%
  filter(rating >= samsung_stats$mean - samsung_stats$sd) %>%
  filter(rating <= samsung_stats$mean + samsung_stats$sd) %>%
  summarise(prop_within_1sd = n() / nrow(samsung_ratings))
```
2SD
```{r}
samsung_ratings %>%
  filter(rating >= samsung_stats$mean - (2 * samsung_stats$sd)) %>%
  filter(rating <= samsung_stats$mean + (2 * samsung_stats$sd)) %>%
  summarise(prop_within_2sd = n() / nrow(samsung_ratings))
```
3SD
```{r}
samsung_ratings %>%
  filter(rating >= samsung_stats$mean - (3 * samsung_stats$sd)) %>%
  filter(rating <= samsung_stats$mean + (3 * samsung_stats$sd)) %>%
  summarise(prop_within_3sd = n() / nrow(samsung_ratings))
```
The percentages for the Samsung data are 79-92-98 which is comparable with 
those expected for a normal distribution (68-95-99.7)
